//from a1 and a7, all result are undefined because in plain JS there is no datatype
//check generated js file
var a1;
console.log("type of a1 " + typeof (a1) + " and its value is " + a1);
var a2;
console.log("type of a2 " + typeof (a2) + " and its value is " + a2);
var a3;
console.log("type of a3 " + typeof (a3) + " and its value is " + a3);
var a4;
console.log("type of a4 " + typeof (a4) + " and its value is " + a4);
var a5;
console.log("type of a5 " + typeof (a5) + " and its value is " + a5);
var a6;
console.log("type of a6 " + typeof (a6) + " and its value is " + a6);
var a7;
console.log("type of a7 " + typeof (a7) + " and its value is " + a7);
var a8 = 100;
console.log("type of a8 " + typeof (a8) + " and its value is " + a8);
var a8a = "Maruti";
console.log("type of a8a " + typeof (a8a) + " and its value is " + a8a);
var a8b = true;
console.log("type of a8b " + typeof (a8b) + " and its value is " + a8b);
var a9 = 200;
console.log("type of a9 " + typeof (a9) + " and its value is " + a9);
var a10 = "Vijay";
console.log("type of a10 " + typeof (a10) + " and its value is " + a10);
var a11 = false;
console.log("type of a11 " + typeof (a11) + " and its value is " + a11);
// var a12 : boolean = "Ram";
// console.log("type of a12 " + typeof (a12) + " and its value is " + a12);
